# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4de5af46b7a28ba55c68a384591620805b59221359f566637dcdb0ce5d13c26c97ac417858e6468cc491a1e235cf61feeb52189dcdca39121f2da86442dcae16

test:
  secret_key_base: 46b17080a118b6b6a5a08be61c92f6bdf9187e62936b051dedd211f06bf68b6ededda7b18ac73e81aece174d2c4cffeeffea19f13efef91663a26b9f94516a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
